// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsrqFMfLZXJAbY8D6BgUTefz2bqAJJeDY',
    appId: '1:194984246224:web:0bbb3713fcc54624c217d5',
    messagingSenderId: '194984246224',
    projectId: 'tarifburada-fc7f1',
    authDomain: 'tarifburada-fc7f1.firebaseapp.com',
    storageBucket: 'tarifburada-fc7f1.firebasestorage.app',
    measurementId: 'G-2NT9768P0X',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgGNb16J53EhVNg5cCdNUdlf5jvy8j8y8',
    appId: '1:194984246224:ios:a01e56b79582ea46c217d5',
    messagingSenderId: '194984246224',
    projectId: 'tarifburada-fc7f1',
    storageBucket: 'tarifburada-fc7f1.firebasestorage.app',
    iosBundleId: 'com.example.tarifburda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgGNb16J53EhVNg5cCdNUdlf5jvy8j8y8',
    appId: '1:194984246224:ios:a01e56b79582ea46c217d5',
    messagingSenderId: '194984246224',
    projectId: 'tarifburada-fc7f1',
    storageBucket: 'tarifburada-fc7f1.firebasestorage.app',
    iosBundleId: 'com.example.tarifburda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsrqFMfLZXJAbY8D6BgUTefz2bqAJJeDY',
    appId: '1:194984246224:web:086a525342f1a79ac217d5',
    messagingSenderId: '194984246224',
    projectId: 'tarifburada-fc7f1',
    authDomain: 'tarifburada-fc7f1.firebaseapp.com',
    storageBucket: 'tarifburada-fc7f1.firebasestorage.app',
    measurementId: 'G-0ZW8N64RLN',
  );
}
